from django import forms


class CartForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'placeholder': 'Ваше имя'
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'placeholder': 'Ваша фамилия'
    }))

    COUNTRY_CHOICES = [('UZ', 'Узбекистан'),
                       ('AF', 'Афганистан'),
                       ('AL', 'Албания'),
                       ('DZ', 'Алжир'),
                       ('AS', 'Американское Самоа'),
                       ('AD', 'Андорра'),
                       ('AO', 'Ангола'),
                       ('AI', 'Ангилья'),
                       ('AQ', 'Антарктида'),
                       ('AG', 'Антигуа и Барбуда'),
                       ('AR', 'Аргентина'),
                       ('AM', 'Армения'), ('AW', 'Аруба'),
                       ('AU', 'Австралия'), ('AT', 'Австрия'),
                       ('AZ', 'Азербайджан'), ('BS', 'Багамы'),
                       ('BH', 'Бахрейн'), ('BD', 'Бангладеш'),
                       ('BB', 'Барбадос'), ('BY', 'Беларусь'),
                       ('BE', 'Бельгия'), ('BZ', 'Белиз'),
                       ('BJ', 'Бенин'), ('BM', 'Бермудские острова'),
                       ('BT', 'Бутан'), ('BO', 'Боливия'),
                       ('BA', 'Босния и Герцеговина'),
                       ('BW', 'Ботсвана'), ('BR', 'Бразилия'), ('IO', 'Британская территория Индийского океана'),
                       ('VG', 'Британские Виргинские острова'), ('BN', 'Бруней'), ('BG', 'Болгария'),
                       ('BF', 'Буркина-Фасо'), ('BI', 'Бурунди'), ('CV', 'Кабо-Верде'), ('KH', 'Камбоджа'),
                       ('CM', 'Камерун'), ('CA', 'Канада'), ('KY', 'Каймановы острова'),
                       ('CF', 'Центральноафриканская Республика'), ('TD', 'Чад'), ('CL', 'Чили'), ('CN', 'Китай'),
                       ('CO', 'Колумбия'), ('KM', 'Коморы'), ('CD', 'Конго (Демократическая Республика)'),
                       ('CG', 'Конго (Республика)'), ('CK', 'Острова Кука'), ('CR', 'Коста-Рика'), ('HR', 'Хорватия'),
                       ('CU', 'Куба'), ('CY', 'Кипр'), ('CZ', 'Чехия'), ('CI', "Кот-д'Ивуар"), ('DK', 'Дания'),
                       ('DJ', 'Джибути'), ('DM', 'Доминика'), ('DO', 'Доминиканская Республика'), ('EC', 'Эквадор'),
                       ('EG', 'Египет'), ('SV', 'Сальвадор'), ('GQ', 'Экваториальная Гвинея'), ('ER', 'Эритрея'),
                       ('EE', 'Эстония'), ('SZ', 'Эсватини'), ('ET', 'Эфиопия'), ('FK', 'Фолклендские острова'),
                       ('FO', 'Фарерские острова'), ('FJ', 'Фиджи'), ('FI', 'Финляндия'), ('FR', 'Франция'),
                       ('GF', 'Французская Гвиана'), ('PF', 'Французская Полинезия'),
                       ('TF', 'Французские Южные и Антарктические территории'), ('GA', 'Габон'), ('GM', 'Гамбия'),
                       ('GE', 'Грузия'), ('DE', 'Германия'), ('GH', 'Гана'), ('GI', 'Гибралтар'), ('GR', 'Греция'),
                       ('GL', 'Гренландия'), ('GD', 'Гренада'), ('GP', 'Гваделупа'), ('GU', 'Гуам'),
                       ('GT', 'Гватемала'), ('GG', 'Гернси'), ('GN', 'Гвинея'), ('GW', 'Гвинея-Бисау'),
                       ('GY', 'Гайана'), ('HT', 'Гаити'), ('VA', 'Ватикан'), ('HN', 'Гондурас'), ('HK', 'Гонконг'),
                       ('HU', 'Венгрия'), ('IS', 'Исландия'), ('IN', 'Индия'), ('ID', 'Индонезия'), ('IR', 'Иран'),
                       ('IQ', 'Ирак'), ('IE', 'Ирландия'), ('IM', 'Остров Мэн'), ('IL', 'Израиль'), ('IT', 'Италия'),
                       ('JM', 'Ямайка'), ('JP', 'Япония'), ('JE', 'Джерси'), ('JO', 'Иордания'), ('KZ', 'Казахстан'),
                       ('KE', 'Кения'), ('KI', 'Кирибати'), ('KW', 'Кувейт'), ('KG', 'Кыргызстан'), ('LA', 'Лаос'),
                       ('LV', 'Латвия'), ('LB', 'Ливан'), ('LS', 'Лесото'), ('LR', 'Либерия'), ('LY', 'Ливия'),
                       ('LI', 'Лихтенштейн'), ('LT', 'Литва'), ('LU', 'Люксембург'), ('MO', 'Макао'),
                       ('MG', 'Мадагаскар'), ('MW', 'Малави'), ('MY', 'Малайзия'), ('MV', 'Мальдивы'), ('ML', 'Мали'),
                       ('MT', 'Мальта'), ('MH', 'Маршалловы острова'), ('MQ', 'Мартиника'), ('MR', 'Мавритания'),
                       ('MU', 'Маврикий'), ('YT', 'Майотта'), ('MX', 'Мексика'),
                       ('FM', 'Федеративные Штаты Микронезии'), ('MD', 'Молдова'), ('MC', 'Монако'), ('MN', 'Монголия'),
                       ('ME', 'Черногория'), ('MS', 'Монтсеррат'), ('MA', 'Марокко'), ('MZ', 'Мозамбик'),
                       ('MM', 'Мьянма'), ('NA', 'Намибия'), ('NR', 'Науру'), ('NP', 'Непал'), ('NL', 'Нидерланды'),
                       ('NC', 'Новая Каледония'), ('NZ', 'Новая Зеландия'), ('NI', 'Никарагуа'), ('NE', 'Нигер'),
                       ('NG', 'Нигерия'), ('NU', 'Ниуэ'), ('NF', 'Остров Норфолк'), ('KP', 'КНДР'),
                       ('MK', 'Северная Македония'), ('NO', 'Норвегия'), ('OM', 'Оман'), ('PK', 'Пакистан'),
                       ('PW', 'Палау'), ('PS', 'Палестина'), ('PA', 'Панама'), ('PG', 'Папуа — Новая Гвинея'),
                       ('PY', 'Парагвай'), ('PE', 'Перу'), ('PH', 'Филиппины'), ('PN', 'Питкэрн'), ('PL', 'Польша'),
                       ('PT', 'Португалия'), ('PR', 'Пуэрто-Рико'), ('QA', 'Катар'), ('RE', 'Реюньон'),
                       ('RO', 'Румыния'), ('RU', 'Россия'), ('RW', 'Руанда'), ('WS', 'Самоа'), ('SM', 'Сан-Марино'),
                       ('ST', 'Сан-Томе и Принсипи'), ('SA', 'Саудовская Аравия'), ('SN', 'Сенегал'), ('RS', 'Сербия'),
                       ('SC', 'Сейшельские Острова'), ('SL', 'Сьерра-Леоне'), ('SG', 'Сингапур'), ('SX', 'Синт-Мартен'),
                       ('SK', 'Словакия'), ('SI', 'Словения'), ('SB', 'Соломоновы острова'), ('SO', 'Сомали'),
                       ('ZA', 'Южная Африка'), ('GS', 'Южная Георгия и Южные Сандвичевы острова'),
                       ('KR', 'Южная Корея'), ('SS', 'Южный Судан'), ('ES', 'Испания'), ('LK', 'Шри-Ланка'),
                       ('BL', 'Сен-Бартелеми'), ('SH', 'Острова Святой Елены, Вознесения и Тристан-да-Кунья'),
                       ('KN', 'Сент-Китс и Невис'), ('LC', 'Сент-Люсия'), ('MF', 'Сен-Мартен'),
                       ('PM', 'Сен-Пьер и Микелон'), ('VC', 'Сент-Винсент и Гренадины'), ('SD', 'Судан'),
                       ('SR', 'Суринам'), ('SJ', 'Шпицберген и Ян-Майен'), ('SE', 'Швеция'), ('CH', 'Швейцария'),
                       ('SY', 'Сирия'), ('TW', 'Тайвань'), ('TJ', 'Таджикистан'), ('TZ', 'Танзания'), ('TH', 'Таиланд'),
                       ('TL', 'Восточный Тимор'), ('TG', 'Того'), ('TK', 'Токелау'), ('TO', 'Тонга'),
                       ('TT', 'Тринидад и Тобаго'), ('TN', 'Тунис'), ('TR', 'Турция'), ('TM', 'Туркмения'),
                       ('TC', 'Острова Теркс и Кайкос'), ('TV', 'Тувалу'), ('UG', 'Уганда'), ('UA', 'Украина'),
                       ('AE', 'Объединенные Арабские Эмираты'), ('GB', 'Великобритания'),
                       ('UM', 'Внешние малые острова США'), ('VI', 'Виргинские Острова (США)'), ('UY', 'Уругвай'),
                       ('VU', 'Вануату'), ('VE', 'Венесуэла'), ('VN', 'Вьетнам'), ('WF', 'Уоллис и Футуна'),
                       ('EH', 'Западная Сахара'), ('YE', 'Йемен'), ('ZM', 'Замбия'), ('ZW', 'Зимбабве')]

    country = forms.ChoiceField(choices=COUNTRY_CHOICES)

    contact = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'placeholder': 'Номер телефона/WhatsApp/Telegram'
    }))


class CartFormEn(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'placeholder': 'First name'
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'placeholder': 'Last name'
    }))

    COUNTRY_CHOICES = [('UZ', 'Uzbekistan'),
                       ('AF', 'Afghanistan'),
                       ('AL', 'Albania'),
                       ('DZ', 'Algeria'),
                       ('AS', 'American Samoa'),
                       ('AD', 'Andorra'),
                       ('AO', 'Angola'),
                       ('AI', 'Anguilla'),
                       ('AQ', 'Antarctica'),
                       ('AG', 'Antigua and Barbuda'),
                       ('AR', 'Argentina'),
                       ('AM', 'Armenia'),
                       ('AW', 'Aruba'),
                       ('AU', 'Australia'),
                       ('AT', 'Austria'),
                       ('AZ', 'Azerbaijan'),
                       ('BS', 'Bahamas'),
                       ('BH', 'Bahrain'),
                       ('BD', 'Bangladesh'),
                       ('BB', 'Barbados'),
                       ('BY', 'Belarus'),
                       ('BE', 'Belgium'),
                       ('BZ', 'Belize'),
                       ('BJ', 'Benin'),
                       ('BM', 'Bermuda'),
                       ('BT', 'Bhutan'),
                       ('BO', 'Bolivia'),
                       ('BA', 'Bosnia and Herzegovina'),
                       ('BW', 'Botswana'),
                       ('BR', 'Brazil'),
                       ('IO', 'British Indian Ocean Territory'),
                       ('VG', 'British Virgin Islands'),
                       ('BN', 'Brunei'),
                       ('BG', 'Bulgaria'),
                       ('BF', 'Burkina Faso'),
                       ('BI', 'Burundi'),
                       ('CV', 'Cape Verde'),
                       ('KH', 'Cambodia'),
                       ('CM', 'Cameroon'),
                       ('CA', 'Canada'),
                       ('KY', 'Cayman Islands'),
                       ('CF', 'Central African Republic'),
                       ('TD', 'Chad'),
                       ('CL', 'Chile'),
                       ('CN', 'China'),
                       ('CO', 'Colombia'),
                       ('KM', 'Comoros'),
                       ('CD', 'Congo (Democratic Republic)'),
                       ('CG', 'Congo (Republic)'),
                       ('CK', 'Cook Islands'),
                       ('CR', 'Costa Rica'),
                       ('HR', 'Croatia'),
                       ('CU', 'Cuba'),
                       ('CY', 'Cyprus'),
                       ('CZ', 'Czech Republic'),
                       ('CI', "Côte d'Ivoire"),
                       ('DK', 'Denmark'),
                       ('DJ', 'Djibouti'),
                       ('DM', 'Dominica'),
                       ('DO', 'Dominican Republic'),
                       ('EC', 'Ecuador'),
                       ('EG', 'Egypt'),
                       ('SV', 'El Salvador'),
                       ('GQ', 'Equatorial Guinea'),
                       ('ER', 'Eritrea'),
                       ('EE', 'Estonia'),
                       ('SZ', 'Eswatini'),
                       ('ET', 'Ethiopia'),
                       ('FK', 'Falkland Islands (Malvinas)'),
                       ('FO', 'Faroe Islands'),
                       ('FJ', 'Fiji'),
                       ('FI', 'Finland'),
                       ('FR', 'France'),
                       ('GF', 'French Guiana'),
                       ('PF', 'French Polynesia'),
                       ('TF', 'French Southern and Antarctic Lands'),
                       ('GA', 'Gabon'),
                       ('GM', 'Gambia'),
                       ('GE', 'Georgia'),
                       ('DE', 'Germany'),
                       ('GH', 'Ghana'),
                       ('GI', 'Gibraltar'),
                       ('GR', 'Greece'),
                       ('GL', 'Greenland'),
                       ('GD', 'Grenada'),
                       ('GP', 'Guadeloupe'),
                       ('GU', 'Guam'),
                       ('GT', 'Guatemala'),
                       ('GG', 'Guernsey'),
                       ('GN', 'Guinea'),
                       ('GW', 'Guinea-Bissau'),
                       ('GY', 'Guyana'),
                       ('HT', 'Haiti'),
                       ('VA', 'Vatican City'),
                       ('HN', 'Honduras'),
                       ('HK', 'Hong Kong'),
                       ('HU', 'Hungary'),
                       ('IS', 'Iceland'),
                       ('IN', 'India'),
                       ('ID', 'Indonesia'),
                       ('IR', 'Iran'),
                       ('IQ', 'Iraq'),
                       ('IE', 'Ireland'),
                       ('IM', 'Isle of Man'),
                       ('IL', 'Israel'),
                       ('IT', 'Italy'),
                       ('JM', 'Jamaica'),
                       ('JP', 'Japan'),
                       ('JE', 'Jersey'),
                       ('JO', 'Jordan'),
                       ('KZ', 'Kazakhstan'),
                       ('KE', 'Kenya'),
                       ('KI', 'Kiribati'),
                       ('KW', 'Kuwait'),
                       ('KG', 'Kyrgyzstan'),
                       ('LA', 'Laos'),
                       ('LV', 'Latvia'),
                       ('LB', 'Lebanon'),
                       ('LS', 'Lesotho'),
                       ('LR', 'Liberia'),
                       ('LY', 'Libya'),
                       ('LI', 'Liechtenstein'),
                       ('LT', 'Lithuania'),
                       ('LU', 'Luxembourg'),
                       ('MO', 'Macao'),
                       ('MG', 'Madagascar'),
                       ('MW', 'Malawi'),
                       ('MY', 'Malaysia'),
                       ('MV', 'Maldives'),
                       ('ML', 'Mali'),
                       ('MT', 'Malta'),
                       ('MH', 'Marshall Islands'),
                       ('MQ', 'Martinique'),
                       ('MR', 'Mauritania'),
                       ('MU', 'Mauritius'),
                       ('YT', 'Mayotte'),
                       ('MX', 'Mexico'),
                       ('FM', 'Micronesia (Federated States of)'),
                       ('MD', 'Moldova'),
                       ('MC', 'Monaco'),
                       ('MN', 'Mongolia'),
                       ('ME', 'Montenegro'),
                       ('MS', 'Montserrat'),
                       ('MA', 'Morocco'),
                       ('MZ', 'Mozambique'),
                       ('MM', 'Myanmar'),
                       ('NA', 'Namibia'),
                       ('NR', 'Nauru'),
                       ('NP', 'Nepal'),
                       ('NL', 'Netherlands'),
                       ('NC', 'New Caledonia'),
                       ('NZ', 'New Zealand'),
                       ('NI', 'Nicaragua'),
                       ('NE', 'Niger'),
                       ('NG', 'Nigeria'),
                       ('NU', 'Niue'),
                       ('NF', 'Norfolk Island'),
                       ('KP', 'North Korea'),
                       ('MK', 'North Macedonia'),
                       ('NO', 'Norway'),
                       ('OM', 'Oman'),
                       ('PK', 'Pakistan'),
                       ('PW', 'Palau'),
                       ('PS', 'Palestine'),
                       ('PA', 'Panama'),
                       ('PG', 'Papua New Guinea'),
                       ('PY', 'Paraguay'),
                       ('PE', 'Peru'),
                       ('PH', 'Philippines'),
                       ('PN', 'Pitcairn Islands'),
                       ('PL', 'Poland'),
                       ('PT', 'Portugal'),
                       ('PR', 'Puerto Rico'),
                       ('QA', 'Qatar'),
                       ('RE', 'Réunion'),
                       ('RO', 'Romania'),
                       ('RU', 'Russia'),
                       ('RW', 'Rwanda'),
                       ('WS', 'Samoa'),
                       ('SM', 'San Marino'),
                       ('ST', 'São Tomé and Príncipe'),
                       ('SA', 'Saudi Arabia'),
                       ('SN', 'Senegal'),
                       ('RS', 'Serbia'),
                       ('SC', 'Seychelles'),
                       ('SL', 'Sierra Leone'),
                       ('SG', 'Singapore'),
                       ('SX', 'Sint Maarten'),
                       ('SK', 'Slovakia'),
                       ('SI', 'Slovenia'),
                       ('SB', 'Solomon Islands'),
                       ('SO', 'Somalia'),
                       ('ZA', 'South Africa'),
                       ('GS', 'South Georgia and the South Sandwich Islands'),
                       ('KR', 'South Korea'),
                       ('SS', 'South Sudan'),
                       ('ES', 'Spain'),
                       ('LK', 'Sri Lanka'),
                       ('BL', 'Saint Barthélemy'),
                       ('SH', 'Saint Helena, Ascension and Tristan da Cunha'),
                       ('KN', 'Saint Kitts and Nevis'),
                       ('LC', 'Saint Lucia'),
                       ('MF', 'Saint Martin'),
                       ('PM', 'Saint Pierre and Miquelon'),
                       ('VC', 'Saint Vincent and the Grenadines'),
                       ('SD', 'Sudan'),
                       ('SR', 'Suriname'),
                       ('SJ', 'Svalbard and Jan Mayen'),
                       ('SE', 'Sweden'),
                       ('CH', 'Switzerland'),
                       ('SY', 'Syria'),
                       ('TW', 'Taiwan'),
                       ('TJ', 'Tajikistan'),
                       ('TZ', 'Tanzania'),
                       ('TH', 'Thailand'),
                       ('TL', 'Timor-Leste'),
                       ('TG', 'Togo'),
                       ('TK', 'Tokelau'),
                       ('TO', 'Tonga'),
                       ('TT', 'Trinidad and Tobago'),
                       ('TN', 'Tunisia'),
                       ('TR', 'Turkey'),
                       ('TM', 'Turkmenistan'),
                       ('TC', 'Turks and Caicos Islands'),
                       ('TV', 'Tuvalu'),
                       ('UG', 'Uganda'),
                       ('UA', 'Ukraine'),
                       ('AE', 'United Arab Emirates'),
                       ('GB', 'United Kingdom'),
                       ('UM', 'United States Minor Outlying Islands'),
                       ('VI', 'United States Virgin Islands'),
                       ('UY', 'Uruguay'),
                       ('VU', 'Vanuatu'),
                       ('VE', 'Venezuela'),
                       ('VN', 'Vietnam'),
                       ('WF', 'Wallis and Futuna'),
                       ('EH', 'Western Sahara'),
                       ('YE', 'Yemen'),
                       ('ZM', 'Zambia'),
                       ('ZW', 'Zimbabwe')]

    country = forms.ChoiceField(choices=COUNTRY_CHOICES)

    contact = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'placeholder': 'Phone number/WhatsApp/Telegram'
    }))


class CartFormUz(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'placeholder': 'Ism'
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'placeholder': 'Familiya'
    }))

    COUNTRY_CHOICES = [
        ('UZ', 'Oʻzbekiston'),
        ('AF', 'Afgʻoniston'),
        ('AL', 'Albaniya'),
        ('DZ', 'Jazoir'),
        ('AS', 'Amerika Samoasi'),
        ('AD', 'Andorra'),
        ('AO', 'Angola'),
        ('AI', 'Angilya'),
        ('AQ', 'Antarktika'),
        ('AG', 'Antigua va Barbuda'),
        ('AR', 'Argentina'),
        ('AM', 'Armaniston'),
        ('AW', 'Aruba'),
        ('AU', 'Avstraliya'),
        ('AT', 'Avstriya'),
        ('AZ', 'Oʻzbekiston'),
        ('BS', 'Bagama orollari'),
        ('BH', 'Bahrayn'),
        ('BD', 'Bangladesh'),
        ('BB', 'Barbados'),
        ('BY', 'Belarus'),
        ('BE', 'Belgiya'),
        ('BZ', 'Beliz'),
        ('BJ', 'Benin'),
        ('BM', 'Bermuda orollari'),
        ('BT', 'Butan'),
        ('BO', 'Boliviya'),
        ('BA', 'Bosniya va Gertsegovina'),
        ('BW', 'Botsvana'),
        ('BR', 'Braziliya'),
        ('IO', 'Britaniya Hind okeani boʻyicha hududi'),
        ('VG', 'Britaniya Virgin orollari'),
        ('BN', 'Bruney'),
        ('BG', 'Bolgariya'),
        ('BF', 'Burkina-Faso'),
        ('BI', 'Burundi'),
        ('CV', 'Kabo-Verde'),
        ('KH', 'Kambodja'),
        ('CM', 'Kamerun'),
        ('CA', 'Kanada'),
        ('KY', 'Kayman orollari'),
        ('CF', 'Markaziy Afrika Respublikasi'),
        ('TD', 'Chad'),
        ('CL', 'Chili'),
        ('CN', 'Xitoy'),
        ('CO', 'Kolumbiya'),
        ('KM', 'Komor orollari'),
        ('CD', 'Kongo (Demokratik Respublikasi)'),
        ('CG', 'Kongo (Respublikasi)'),
        ('CK', 'Kuk orollari'),
        ('CR', 'Kosta-Rika'),
        ('HR', 'Xorvatiya'),
        ('CU', 'Kuba'),
        ('CY', 'Kipr'),
        ('CZ', 'Chexiya'),
        ('CI', "Kot-d'Ivuar"),
        ('DK', 'Daniya'),
        ('DJ', 'Jibuti'),
        ('DM', 'Dominika'),
        ('DO', 'Dominikan Respublikasi'),
        ('EC', 'Ekvador'),
        ('EG', 'Misr'),
        ('SV', 'Salvador'),
        ('GQ', 'Ekvatorial Gvineya'),
        ('ER', 'Eritreya'),
        ('EE', 'Estoniya'),
        ('SZ', 'Svazilend'),
        ('ET', 'Efiopiya'),
        ('FK', 'Folklend orollari'),
        ('FO', 'Farer orollari'),
        ('FJ', 'Fiji'),
        ('FI', 'Finlandiya'),
        ('FR', 'Fransiya'),
        ('GF', 'Fransuz Gvianasi'),
        ('PF', 'Fransuz Polineziyasi'),
        ('TF', 'Fransuz Janubiy va Antarktika hududlari'),
        ('GA', 'Gabon'),
        ('GM', 'Gambiya'),
        ('GE', 'Gruziya'),
        ('DE', 'Germaniya'),
        ('GH', 'Gana'),
        ('GI', 'Gibraltar'),
        ('GR', 'Yunoniston'),
        ('GL', 'Grenlandiya'),
        ('GD', 'Grenada'),
        ('GP', 'Guadelupa'),
        ('GU', 'Guam'),
        ('GT', 'Gvatemala'),
        ('GG', 'Gernsi'),
        ('GN', 'Gvineya'),
        ('GW', 'Gvineya-Bisau'),
        ('GY', 'Gayana'),
        ('HT', 'Gaiti'),
        ('VA', 'Vatikan'),
        ('HN', 'Gonduras'),
        ('HK', 'Gonkong'),
        ('HU', 'Vengriya'),
        ('IS', 'Islandiya'),
        ('IN', 'Hindiston'),
        ('ID', 'Indoneziya'),
        ('IR', 'Eron'),
        ('IQ', 'Iroq'),
        ('IE', 'Irlandiya'),
        ('IM', 'Men oroli'),
        ('IL', 'Isroil'),
        ('IT', 'Italiya'),
        ('JM', 'Yamayka'),
        ('JP', 'Yaponiya'),
        ('JE', 'Jersi'),
        ('JO', 'Urdun'),
        ('KZ', 'Qozogʻiston'),
        ('KE', 'Keniya'),
        ('KI', 'Kiribati'),
        ('KW', 'Quvayt'),
        ('KG', 'Qirgʻiziston'),
        ('LA', 'Laos'),
        ('LV', 'Latviya'),
        ('LB', 'Livan'),
        ('LS', 'Lesoto'),
        ('LR', 'Liberiya'),
        ('LY', 'Liviya'),
        ('LI', 'Lixtenshteyn'),
        ('LT', 'Litva'),
        ('LU', 'Lyuksemburg'),
        ('MO', 'Makao'),
        ('MG', 'Madagaskar'),
        ('MW', 'Malavi'),
        ('MY', 'Malayziya'),
        ('MV', 'Maldiv orollari'),
        ('ML', 'Mali'),
        ('MT', 'Malta'),
        ('MH', 'Marshall orollari'),
        ('MQ', 'Martinika'),
        ('MR', 'Mavritaniya'),
        ('MU', 'Mavrikiy'),
        ('YT', 'Mayotta'),
        ('MX', 'Meksika'),
        ('FM', 'Mikroneziya Federativ Shtatlari'),
        ('MD', 'Moldova'),
        ('MC', 'Monako'),
        ('MN', 'Mongoliya'),
        ('ME', 'Chernogoriya'),
        ('MS', 'Montserrat'),
        ('MA', 'Marokash'),
        ('MZ', 'Mozambik'),
        ('MM', 'Myanma'),
        ('NA', 'Namibiya'),
        ('NR', 'Nauru'),
        ('NP', 'Nepal'),
        ('NL', 'Niderlandiya'),
        ('NC', 'Yangi Kaledoniya'),
        ('NZ', 'Yangi Zelandiya'),
        ('NI', 'Nikaragua'),
        ('NE', 'Niger'),
        ('NG', 'Nigeriya'),
        ('NU', 'Niue'),
        ('NF', 'Norfolk oroli'),
        ('KP', 'Shimoliy Koreya'),
        ('MK', 'Shimoliy Makedoniya'),
        ('NO', 'Norvegiya'),
        ('OM', 'Ummon'),
        ('PK', 'Pokiston'),
        ('PW', 'Palau'),
        ('PS', 'Falastin'),
        ('PA', 'Panama'),
        ('PG', 'Papua - Yangi Gvineya'),
        ('PY', 'Paragvay'),
        ('PE', 'Peru'),
        ('PH', 'Filippin'),
        ('PN', 'Pitkern'),
        ('PL', 'Polsha'),
        ('PT', 'Portugaliya'),
        ('PR', 'Puerto-Riko'),
        ('QA', 'Qatar'),
        ('RE', 'Reyunion'),
        ('RO', 'Ruminiya'),
        ('RU', 'Rossiya'),
        ('RW', 'Ruanda'),
        ('WS', 'Samoa'),
        ('SM', 'San-Marino'),
        ('ST', 'San-Tome va Prinsipi'),
        ('SA', 'Saudiya Arabistoni'),
        ('SN', 'Senegal'),
        ('RS', 'Serbiya'),
        ('SC', 'Seyshel orollari'),
        ('SL', 'Syerra-Leone'),
        ('SG', 'Singapur'),
        ('SX', 'Sint-Marten'),
        ('SK', 'Slovakiya'),
        ('SI', 'Sloveniya'),
        ('SB', 'Solomon orollari'),
        ('SO', 'Somali'),
        ('ZA', 'Janubiy Afrika'),
        ('GS', 'Janubiy Georgiya va Janubiy Sandvich orollari'),
        ('SS', 'Janubiy Sudan'),
        ('ES', 'Ispaniya'),
        ('LK', 'Shri-Lanka'),
        ('SD', 'Sudan'),
        ('SR', 'Surinam'),
        ('SE', 'Shvetsiya'),
        ('CH', 'Shveytsariya'),
        ('SY', 'Suriya'),
        ('TW', 'Tayvan'),
        ('TJ', 'Tojikiston'),
        ('TZ', 'Tanzaniya'),
        ('TH', 'Tailand'),
        ('TL', 'Sharqiy Timor'),
        ('TG', 'Togo'),
        ('TK', 'Tokelau'),
        ('TO', 'Tonga'),
        ('TT', 'Trinidad va Tobago'),
        ('TN', 'Tunis'),
        ('TR', 'Turkiya'),
        ('TM', 'Turkmaniston'),
        ('TC', 'Terks va Kaykos orollari'),
        ('TV', 'Tuvalu'),
        ('UG', 'Uganda'),
        ('UA', 'Ukraina'),
        ('AE', 'Birlashgan Arab Amirliklari'),
        ('GB', 'Buyuk Britaniya'),
        ('US', 'Amerika Qoʻshma Shtatlari'),
        ('UY', 'Urugvay'),
        ('VU', 'Vanuatu'),
        ('VE', 'Venesuela'),
        ('VN', 'Vyetnam'),
        ('WF', 'Uollis va Futuna'),
        ('EH', 'Gʻarbiy Sahroi Kabir'),
        ('YE', 'Yaman'),
        ('ZM', 'Zambiya'),
        ('ZW', 'Zimbabve')
    ]

    country = forms.ChoiceField(choices=COUNTRY_CHOICES)

    contact = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'placeholder': 'Telefon raqam/WhatsApp/Telegram'
    }))
