# Generated by Django 5.0.4 on 2024-05-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_countblogabout_aboutus_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
