# Generated by Django 5.0.4 on 2024-05-11 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_countblogabout_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Блок о нас', 'verbose_name_plural': 'Блоки о нас'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='countblogabout',
            options={'verbose_name': 'Поле о нас', 'verbose_name_plural': 'Поля о нас'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.countblogabout', verbose_name='Поле информации'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока о нас'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название коллекции'),
        ),
        migrations.AlterField(
            model_name='countblogabout',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Фото поля'),
        ),
        migrations.AlterField(
            model_name='countblogabout',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок поля'),
        ),
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.collection', verbose_name='Коллекция товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.material', verbose_name='Материал товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название материала'),
        ),
    ]
