# Generated by Django 5.0.4 on 2024-05-12 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_collection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogsAbout', to='backend.countblogabout', verbose_name='Поле информации'),
        ),
    ]
