# Generated by Django 5.0.4 on 2024-05-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_aboutus_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание {en}'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание {uz}'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока о нас {en}'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока о нас {uz}'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название коллекции {en}'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название коллекции {uz}'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара {en}'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара {uz}'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название товара {en}'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название товара {uz}'),
        ),
        migrations.AddField(
            model_name='material',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название материала {en}'),
        ),
        migrations.AddField(
            model_name='material',
            name='name_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название материала {uz}'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
