# Generated by Django 5.0.6 on 2024-05-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_orderitem_order_remove_orderitem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='ind',
            field=models.PositiveIntegerField(default=1, verbose_name='Индексация элемента'),
            preserve_default=False,
        ),
    ]
