# Generated by Django 5.0.6 on 2024-09-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_sum',
            field=models.TextField(blank=True, null=True, verbose_name='Цена товара в сумах '),
        ),
    ]
