# Generated by Django 5.0.6 on 2024-09-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_item_price_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Цена в сумах'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена товара в долларах'),
        ),
    ]
